name: Update Menu Otomatis

on:
  push:
    branches: [ main ] # Pastikan nama branch kamu 'main', jika 'master' ganti jadi master
    paths:
      - 'data_menu/**'
      - 'generate_menu.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Mengambil seluruh histori agar bisa push

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Menu JSON
        run: python generate_menu.py

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add menu.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update menu.json" && git push origin main)
